// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartHome.Infrastructure.Data;

#nullable disable

namespace SmartHome.Infrastructure.Migrations
{
    [DbContext(typeof(SmartHomeDbContext))]
    [Migration("20260324181211_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartHome.Domain.Entities.ActionLog", b =>
                {
                    b.Property<Guid>("LogsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("logs_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_name");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("log_type");

                    b.Property<Guid?>("LogdeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("logdevice_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("LogsId");

                    b.HasIndex("LogdeviceId");

                    b.ToTable("action_logs", (string)null);
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<Guid>("DroomId")
                        .HasColumnType("uuid")
                        .HasColumnName("droom_id");

                    b.Property<string>("FeedKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feed_key");

                    b.Property<DateTime>("InstallDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("install_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.HasKey("DeviceId");

                    b.HasIndex("DroomId");

                    b.HasIndex("FeedKey")
                        .IsUnique();

                    b.ToTable("devices", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("RuserId")
                        .HasColumnType("uuid")
                        .HasColumnName("ruser_id");

                    b.HasKey("RoomId");

                    b.HasIndex("RuserId");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.SensorData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("SensorDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_device_id");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("SensorDeviceId");

                    b.ToTable("sensor_data", (string)null);
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.OutputDevice", b =>
                {
                    b.HasBaseType("SmartHome.Domain.Entities.Device");

                    b.Property<bool>("Auto")
                        .HasColumnType("boolean")
                        .HasColumnName("auto");

                    b.Property<string>("OnOffState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("onoff_state");

                    b.ToTable("output_devices", (string)null);
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.Sensor", b =>
                {
                    b.HasBaseType("SmartHome.Domain.Entities.Device");

                    b.Property<decimal?>("ThresholdMax")
                        .HasColumnType("numeric")
                        .HasColumnName("threshold_max");

                    b.Property<decimal?>("ThresholdMin")
                        .HasColumnType("numeric")
                        .HasColumnName("threshold_min");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.ActionLog", b =>
                {
                    b.HasOne("SmartHome.Domain.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("LogdeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.Device", b =>
                {
                    b.HasOne("SmartHome.Domain.Entities.Room", "Room")
                        .WithMany("Devices")
                        .HasForeignKey("DroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.Room", b =>
                {
                    b.HasOne("SmartHome.Domain.Entities.User", "User")
                        .WithMany("Rooms")
                        .HasForeignKey("RuserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.SensorData", b =>
                {
                    b.HasOne("SmartHome.Domain.Entities.Sensor", "Sensor")
                        .WithMany("SensorData")
                        .HasForeignKey("SensorDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.OutputDevice", b =>
                {
                    b.HasOne("SmartHome.Domain.Entities.Device", null)
                        .WithOne()
                        .HasForeignKey("SmartHome.Domain.Entities.OutputDevice", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.Sensor", b =>
                {
                    b.HasOne("SmartHome.Domain.Entities.Device", null)
                        .WithOne()
                        .HasForeignKey("SmartHome.Domain.Entities.Sensor", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.Room", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.User", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.Sensor", b =>
                {
                    b.Navigation("SensorData");
                });
#pragma warning restore 612, 618
        }
    }
}
